---
# tasks file for ansible-role-wireguard

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Include configure-{{ ansible_os_family }}.yml"
  include: "configure-{{ ansible_os_family }}.yml"
